sudo: false

language: node_js

node_js:
  - 5.1.1
  
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - mongodb-upstart
      - ubuntu-toolchain-r-test
    packages:
      - mongodb-org-server
      - g++-4.8

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export COCO_TRAVIS_TEST=1
  - npm install -g npm@latest

before_script:
  - npm update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "node index.js --unittest &"
  - n=0
  - until [ $n -ge 60 ]; do curl http://localhost:3000 && break; n=$[$n+1]; sleep 1; done

script:
  - "./node_modules/karma/bin/karma start --browsers Firefox --single-run --reporters dots"
  - "npm run jasmine"
  - "npm run coverage"

after_script:
  - "npm install coveralls && cat ./coverage/lcov.info | coveralls"

notifications:
  slack:
    rooms:
      - secure: dv1zozcLo/gGb1i1OeKKLQgjLagW3jqhkEIiZrVbubfRMrrHouZwtlg1HDVc2GOzP1yCaUOYOLBqT3lTE9CKt4pE8k3p0gJ77j1rHxTyeYny2ETq4w5sXak8ju8M3EDnj+Au2NWWrGiD0YkIUnF5vxzKUc1pkS+vDSWR2ORkOrU=
    template:
      - Tests failed <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} <!here>
    on_success: never
    on_failure: always
    on_start: never
    on_pull_requests: false
